### ISSUE TITLE
Semantic description is not specified for the same robot as the URDF

### ISSUE THREAD

**Issue by Daniel-CSU** [MrLacquer/ur3-moveit-test#1]
When I run this command(roslaunch ur3_moveit_config ur3_moveit_planning_execution.launch sim:=true), I get an error:
process[move_group-1]: started with pid [8103]
[ERROR] [1600248068.910071092]: Semantic description is not specified for the same robot as the URDF
[ INFO] [1600248068.916239487]: Loading robot model 'husky'...
[ERROR] [1600248069.048917344]: Semantic description is not specified for the same robot as the URDF
[ INFO] [1600248069.049008263]: Loading robot model 'husky'...
[ INFO] [1600248069.326997770, 4069.670000000]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1600248069.329352170, 4069.671000000]: MoveGroup debug mode is OFF
Starting context monitors...

How to solve it？Thanks

**Comment by hj26-park** [comment]
Follow on your error, there is some problem in 'husky' URDF.
Please check about that.

Your errors have not related to this package.

Thanks.
