### ISSUE TITLE
Manipulator movement

### ISSUE THREAD

**Issue by Daniel-CSU** [MrLacquer/ur3-moveit-test#2]
Only UR3 is in the given code_ demo.py It can run normally. How to set "home" and "zeros"

**Comment by hj26-park** [comment]
Hi,

The 'home' and 'zeros' are setting on the "[moveit_setup_assistance - Step 5: Add Robot Poses](http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/setup_assistant/setup_assistant_tutorial.html#step-5-add-robot-poses)".

**Comment by Daniel-CSU** [comment]
I chose to click the "create new moveit configuration package" button,when load a urdf(husky_ur3_manipluator/husky_ur3_gazebo/urdf/ur3_joint_limited_robot.urdf.xacro),it tell me URDF/COLLADA file is not a valid robot model.I'm experimenting with your software package.Could you help me? Thanks

**Comment by hj26-park** [comment]
Hi,

That problem is based on UR3 URDF.
I don't have a solution to that problem.
Would you please ask the Universal Robot's git?

Thank you.
