### ISSUE TITLE
ABORTED: Solution found but controller failed during execution

### ISSUE THREAD

**Issue by RodrigoFBernardo** [MrLacquer/ur3-moveit-test#3]
I am trying the code but it doesn't work. I always have the following errors: 

[ INFO] [1614697162.895504878]: ABORTED: Solution found but controller failed during execution

and don't find the target "zeros"

Thanks

**Comment by hj26-park** [comment]
"zero" is a robot pose make by Moveit setup assistance.
please check it this [tutorial](https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html?highlight=setup%20assistance#step-5-add-robot-poses).

Thanks
